MODFLOW-ORG/modflow-devtools

modflow_devtools/fixtures.py
modflow_devtools/misc.py
modflow_devtools/test/test_executables.py
modflow_devtools/test/test_fixtures.py
modflow_devtools/test/test_misc.py

* rename `modflow_devtools.misc.get_models` to `get_model_paths`
* fix `get_model_paths` filtering by package
* sort paths returned by `get_model_paths`
* refactor `get_packages` function
* expand tests

Fix/refactor model-loading fixtures and utilities

---

.github/workflows/release.yml

Update `release.yml` to:
- run when tags are pushed
- auto-create a GitHub release
- publish to PyPI if username/password are provided as repo secrets

refactor(ci): create release and publish to PyPI when tags pushed

---

.github/workflows/ci.yml
modflow_devtools/build.py
modflow_devtools/test/test_build.py
modflow_devtools/test/test_misc.py
setup.cfg

This was originally a member method on the test context class, but it's used in enough places to justify being a standalone utility function like in `mfpymake` IMO. I flip-flopped a few times about whether this should live here, but being able to import from this package means MODFLOW 6 distribution scripts don't have to use `mfpymake`, adjust the system path to import from `autotest`, or duplicate a similar function.

feat(build): restore meson_build function

---

README.md
modflow_devtools/case.py
modflow_devtools/download.py
modflow_devtools/misc.py
modflow_devtools/test/test_case.py
modflow_devtools/test/test_download.py

* bear `GITHUB_TOKEN` in `download_and_unzip()` if env var is set
* fix `Case` examples in `README.md` and add/update `Case` tests
* add util fns for release/asset/artifact retrieval from GH API

fix(misc): fix multiple issues

---

.github/workflows/ci.yml
.github/workflows/release.yml
DEVELOPER.md
README.md
setup.cfg

Drop Python 3.7 support and add Python 3.11, aiming to stay in sync [with FloPy](https://github.com/modflowpy/flopy/pull/1662). Also update `setup.cfg` flake8 section, update Python versions in CI test matrix, and briefly describe Python version support strategy in `DEVELOPER.md`.

refactor: drop Python 3.7, add Python 3.11

---

.github/workflows/release.yml

Excludes the `CHANGELOG.md` generated by `git-cliff-action` since we store cumulative changelog in `HISTORY.md`

fix(release): exclude intermediate changelog

---

README.md
docs/md/fixtures.md
modflow_devtools/fixtures.py

Fixes the `example_scenario` fixture which loads example models from the [`MODFLOW-USGS/modflow6-examples`](https://github.com/MODFLOW-USGS/modflow6-examples) repo. Previously models in the examples repository were not enumerated correctly and test cases requiring the fixture would be improperly skipped

fix(fixtures): fix example_scenario fixture loading

---

docs/md/fixtures.md
modflow_devtools/fixtures.py
modflow_devtools/misc.py
modflow_devtools/test/test_fixtures.py
modflow_devtools/test/test_misc.py

* refactor model-loading fixtures as `Path` to namefile rather than model directory, affects the following fixtures
* `test_model_mf6`
* `test_model_mf5to6`
* `large_test_model`
* split `get_model_paths()` utility function into
* `get_model_dir_paths()`
* `get_namefile_paths()`
* add/update tests
This PR introduces a breaking change for model-loading fixtures. Previously the fixtures were `Path`s to the model directory, i.e. the folder containing the model's namefile. This caused ambiguity and/or duplication if a folder contained multiple namefiles. Since namefiles contain relative paths to inputs, it should be sufficient to provide the namefile path alone to test functions.
This PR does not change the `example_scenario` fixture, which is still a `Tuple[str, List[Path]]` mapping scenario …

refactor(fixtures): fix/refactor model-loading fixtures

---

setup.cfg

The development status was incorrectly set to `Production/Stable` but should reflect the project's early/pre-release state

docs(package): fix package development status

---

HISTORY.md
cliff.toml

Commit links in `HISTORY.md` (and associated config in `cliff.toml`) mistakenly referred to the `modflowpy/flopy` repo, fix them

fix(release): fix changelog commit links

---

docs/conf.py
docs/md/fixtures.md
modflow_devtools/fixtures.py
modflow_devtools/misc.py
modflow_devtools/test/test_misc.py

Revert the naming change in 0.1.0 from `get_model_paths()` -> `get_model_dir_paths()`. The former is more concise anyway and this avoids breaking downstream usages (e.g. [the nightly build](https://github.com/MODFLOW-USGS/modflow6-nightly-build/actions/runs/3804393985/jobs/6471976509)).

refactor(utilities): restore get_model_paths function name

---

DEVELOPER.md
docs/md/cases.md
docs/md/executables.md
docs/md/install.md

- clarify usage examples for `Executables`
- mention function to create default `Executables` config for modflow6 testing
- simplify `Case` docs wording
- fix instructions for importing as pytest plugin (trailing `.fixtures` was missing)
- fix TOC in `DEVELOPER.md`

docs: update/expand docs, fix TOC in DEVELOPER.md

---

docs/md/act.md
docs/md/fixtures.md
docs/md/install.md
modflow_devtools/fixtures.py
modflow_devtools/test/test_build.py
modflow_devtools/test/test_fixtures.py
modflow_devtools/test/test_misc.py

- Search for model repos in a default location relative to the working directory. If the consuming project's tests are run from an `autotest` folder in the project root, and model repos live next to the consuming project, models will be found by fixtures. This makes model-finding fixtures usable without setting the  `REPOS_PATH` environment variable, which was previously required.
- Don't skip any models by default when loading via fixtures. Consuming projects can `pytest.skip()` in the test function or use `get_model_paths()` or `get_namefile_paths()` directly if more control is required over which models are loaded.
- Expand/clarify documentation

refactor(fixtures): add default external model repo location

---

docs/md/fixtures.md

Adds docs for filtering external model tests by model name and packages used.

docs(fixtures): add docs for model filtering by name/package

---

modflow_devtools/misc.py

Now that this project requires Python >= 3.8 (#25), [`import.metadata`](https://docs.python.org/3/library/importlib.metadata.html) can be used instead of [`pkg_resources`](https://setuptools.pypa.io/en/latest/pkg_resources.html).

refactor(has_pkg): use import.metadata instead of pkg_resources

---

docs/md/download.md

Mention `GITHUB_TOKEN` for GitHub API utilities.

docs: update docs for download utilities

---

modflow_devtools/misc.py
modflow_devtools/test/test_misc.py

Previously the `get_packages(namefile_path)` function was not smart enough to find and search component model namefiles when given a simulation namefile &mdash; it only searched the specified namefile, so only GWF, IMS and TDIS would be returned, not the simulation's constituent models' packages. This PR fixes the function, looking in any GWF and GWT model namefiles referenced in a simulation namefile.
This affects the `get_namefile_paths()` and `get_model_paths()` functions, which use `get_packages()` internally. Also makes [filtering external model tests by `--package`](https://modflow-devtools.readthedocs.io/en/latest/md/fixtures.html#filtering-by-package) behave as expected, like the modflow6 autotests' `--pak` option previously behaved, including any component model packages used by …

fix(fixtures): fix package detection/selection

---

docs/md/zip.md
modflow_devtools/test/test_zip.py

Previously `MFZipFile` was untested, add a few test cases for it. Also mention the `compressall()` utility method in the docs.

test(MFZipFile): add tests for MFZipFile, update docs

---

modflow_devtools/fixtures.py
modflow_devtools/test/test_fixtures.py

Previously, keepable temporary directory fixtures did not overwrite existing folders. Needing to manually remove temp folders increases friction for repeated testing/debugging, so this PR updates the `--keep` option to overwrite the specified location.
While this introduces the potential for data loss, presumably users of this package are running tests from an `autotest` folder, which shouldn't contain anything valuable that's not already under version control.

refactor(fixtures): overwrite keepable temp dirs by default

---

docs/md/download.md
modflow_devtools/context.py
modflow_devtools/download.py
modflow_devtools/test/test_download.py
modflow_devtools/zip.py

- add retries for several GitHub API utilities
- refactor default page size/count param values
- switch `quiet` flags to `verbose` for consistency
- lint with updated `black` version
- expand tests
- update docs
Some of the signature changes may break existing usages &mdash; will need to take care to check consuming projects when the next version is released.

refactor(download): refactor GH API utils, add tests, update docs

---

README.md
docs/md/cases.md
docs/md/download.md
docs/md/executables.md
docs/md/fixtures.md

Fix/clarify a few things in docs and README
- simplify some usage examples
- clarify some language describing temp dir fixtures
- to use devtools as a `pytest` plugin, `conftest.py` need not live in the consuming project's root

docs: update/clarify various rtd pages

---

modflow_devtools/executables.py

The  `build_default_exe_dict()` function is a utility to populate the `Executables` fixture with the default binary name/path config used by modflow6 autotests. Previously only a subset of binaries were mapped. Update it for a complete mapping including all downloaded/rebuilt exes. (What constitutes a "complete" mapping will change if the set of binaries included in the core modflow6 or executables distributions change.)

refactor(fixtures): add entries to default exe name/path mapping

---

README.md
scripts/update_version.py

Don't embed the full version string in the readme, since this package isn't on the same review/approval/release cycle as modflow6 and flopy, and tags display the same information

refactor(versioning): don't track version explicitly in readme

---

.github/workflows/ci.yml
modflow_devtools/fixtures.py
modflow_devtools/test/test_download.py

- Improve implementation of external model repo discovery from #80
- Only run network-dependent tests on a single job in CI testing, not the whole matrix. The [rate limit](https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits) for CI is 1000 requests per hour per repo, which this repo likely hit due to parametrized tests for GH API utility functions.

fix(multiple): fix CI and fixture issues

---

docs/md/doctoc.md

Expand the `doctoc` page with installation info

docs: add install and usage docs for node and doctoc

---

modflow_devtools/misc.py
modflow_devtools/test/test_misc.py

Add a utility to temporarily alter the process' environment. Referenced from [this SO answer](https://stackoverflow.com/a/34333710/6514033).

feat(set_env): add set_env contextmanager utility

---

DEVELOPER.md
README.md
docs/md/install.md
pyproject.toml

- make `pytest` dependency optional
- move `numpy` to test dependency

refactor(dependencies): remove them, update readme and dev docs

---

README.md
docs/md/download.md
modflow_devtools/download.py

- convenient for e.g. downloading from URLs which don't correspond to downloaded filename and extract dir

refactor(download_and_unzip): return path to extract locn

---

README.md
docs/md/ostags.md
modflow_devtools/ostags.py
modflow_devtools/test/test_ostags.py

Recently asset names were made consistent across all three main MODFLOW 6 release channels (main repo, executables repo, nightly build) but the repos achieve this separately. Consolidating here will make it easier to change OS tags in future if ever needed.

feat(ostags): add OS tag conversion utilities

---

docs/md/ostags.md
modflow_devtools/misc.py
modflow_devtools/ostags.py
modflow_devtools/test/test_ostags.py

- deprecate `misc.get_ostag()` in favor of `ostags.get_modflow_ostag()`
- deprecate `misc.get_suffixes()` for `ostags.get_binary_suffixes()`
- improve some docstrings
- expand tests
- update docs

refactor(ostags,misc): deprecate fns in misc, add ostags alternatives

---

.github/workflows/ci.yml
conftest.py
modflow_devtools/markers.py
modflow_devtools/misc.py
modflow_devtools/test/test_misc.py
pyproject.toml

* add `strict` param to `has_pkg()` toggling whether to try to import the pkg or only check metadata
* always invalidate/refresh the cache if strict is on
* add `pytest-virtualenv` to test dependencies, test with/without strict
* use `--dist loadfile` with xdist in CI for compatibility
* motivated by https://github.com/modflowpy/flopy/pull/1918, tests marked with `requires_pkg` could fail if a pkg has been installed but is missing dependencies

refactor(has_pkg): introduce strict flag

---

.readthedocs.yml

- use `build.os` as recommended by https://blog.readthedocs.com/use-build-os-config/
- also move python version to `build.tools.python`

docs: update deprecated config in .readthedocs.yml

---

modflow_devtools/fixtures.py
modflow_devtools/test/test_fixtures.py

Tabular data is commonly represented in Python with numpy recarrays and pandas dataframes. FloPy recently added pandas as a core dependency. Work is underway to use pandas internally where expedient and support pandas dataframes across user-facing APIs where numpy recarrays were previously required.
Introduce a `--pandas` (short `-P`) pytest CLI option accepting values: `yes`, `no`, `random`. This controls the value of a boolean `use_pandas` fixture. Motivations:
- allow parametrizing `use_pandas` argument to `MFSimulation` etc
- allow controlling how package input data is provided in tests
Other miscellany:
- some minor cleanup/reorg
- use `dest="KEEP"` when configuring `--keep` option, access option from fixtures with `request.config.option.KEEP`

feat(fixtures): add use_pandas pytest fixture and --pandas CLI arg

---

modflow_devtools/fixtures.py
modflow_devtools/test/test_fixtures.py

Followup on #112, introduce `tabular` fixture with `--tabular` CLI arg accepting `raw`, `recarray`, or `dataframe`. The previously introduced `use_pandas` fixture can condition whether the module under test uses pandas for internal work, the `tabular` fixture can select how input data is provided, leaving open the possibility for alternative representations in future

feat(fixtures): add --tabular pytest CLI arg and corresponding fixture

---

autotest/test_executables.py
docs/md/executables.md
modflow_devtools/executables.py

* add `.get(key, default=None)` method to `Executables` class

feat(executables): support .get(key, default) like dict

---

.github/workflows/ci.yml
README.md
autotest/test_figspec.py
docs/index.rst
docs/md/figspec.md
docs/md/latex.md
modflow_devtools/figspec.py
modflow_devtools/latex.py
pyproject.toml

* move `figspec` and `latex` utility modules from modflow6-examples repository
* add `matplotlib` as optional dependency
* update readme

feat: add latex and plot style utilities

---

autotest/test_misc.py
modflow_devtools/misc.py

Convenience functions for parsing Python literals from `os.environ`, with optional defaults

feat(misc): parse literals from environment variables

---

.gitignore
autotest/test_fixtures.py
modflow_devtools/fixtures.py
modflow_devtools/ostags.py
pyproject.toml
scripts/update_version.py

* pytest 8 sets `request.session.name` to the empty string where previously it was the pytest root workspace name, use `request.config.rootpath.name` instead
* https://github.com/pytest-dev/pytest/releases/tag/8.0.0rc1
* drop `pytest-cases` optional dependency as it is unused and not yet supported by pytest 8
* https://github.com/smarie/python-pytest-cases/issues/330

refactor(fixtures): support pytest>=8, drop pytest-cases dependency

---

.github/workflows/ci.yml
.github/workflows/release.yml
.gitignore

* not always known what next development version will be, just follow recent decision in flopy/modflowapi/pywatershed not to automate the reset PR

ci(release): remove reset step from release workflow

---

autotest/test_ostags.py
docs/md/ostags.md
modflow_devtools/ostags.py

* add `macarm` tag for apple silicon macs
* remove `OSTags` class, refactor `OSTags.convert()` -> `convert_ostag()`
* update docs and tests

feat(ostags): apple silicon

---

docs/md/fixtures.md

* old `test_z0*...` naming has changed
* slightly less verbose usage examples

docs(fixtures): updated outdated mf6 test script reference

---

.github/workflows/ci.yml
autotest/test_build.py
autotest/test_download.py
autotest/test_fixtures.py
autotest/test_markers.py
autotest/test_misc.py
modflow_devtools/download.py
modflow_devtools/fixtures.py
modflow_devtools/imports.py
modflow_devtools/latex.py
modflow_devtools/markers.py
modflow_devtools/misc.py
modflow_devtools/ostags.py
pyproject.toml
scripts/update_version.py

* swap [Ruff](https://docs.astral.sh/ruff/) for black, isort, pylint, flake8
* apply some fixes recommended by ruff's linter
* reformat python files with ruff's default ruleset

chore: switch to ruff, misc linting fixes

---

autotest/test_markers.py
docs/md/markers.md
modflow_devtools/markers.py
modflow_devtools/misc.py

* add `no_parallel` marker to `modflow_devtools.markers` to skip test if xdist is activated
* add `name_map` param to `has_pkg()` function and `requires_pkg` marker &mdash; accommodate packages which don't have a correspondingly named top-level module, e.g. `pytext-xdist` -> `xdist`, `mfpymake` -> `pymake`
* minor refactor in `has_pkg()` and update docstrings

feat(markers): add no_parallel marker, support differing pkg/module names

---

autotest/test_misc.py
modflow_devtools/misc.py

Sort models within each scenario so models can be run in the order returned by `get_model_paths()`, with flow models preceding other model types. This is critical since this function is used to generate scripts for running the examples which are included in the distribution.

fix(get_model_paths): fix model order within scenario

---

autotest/conftest.py
autotest/test_snapshots.py
docs/md/snapshots.md
modflow_devtools/snapshots.py

* add `--snapshot-disable` pytest CLI option to disable snapshot comparisons
* if snapshots are disabled, the snapshot fixture provided to the test function will attest equivalence to anything, e.g. `snapshot == "yes, anything"` returns `True`

feat(snapshots): add --snapshot-disable cli option

---

docs/md/snapshots.md

NumPy 2.0.0 changes the way arrays with object dtype are pickled: https://numpy.org/devdocs/release/2.0.0-notes.html#highlights

docs(snapshots): mention binary snapshot portability issues

---

.github/workflows/ci.yml
autotest/test_misc.py
modflow_devtools/misc.py
pyproject.toml

This fixes a few typos and adds a configuration for codespell, which is also run in CI.
The ruff configuration is simplified (and re-ordered) to remove `target-version` and `include`, but the rules are not revised.

chore: fix typos and add codespell check to CI

---

.github/workflows/ci.yml

The `macos-12` image is deprecated and not supported. Upgrade to `macos-13`, which is still supported.

ci: use macos-13 image instead of macos-12

---

autotest/test_download.py
autotest/test_fixtures.py
autotest/test_misc.py
autotest/test_snapshots.py
autotest/test_zip.py
modflow_devtools/build.py
modflow_devtools/download.py
modflow_devtools/fixtures.py
modflow_devtools/latex.py
modflow_devtools/misc.py
modflow_devtools/ostags.py
pyproject.toml
scripts/update_version.py

There are several refactors combined in this PR:
- Use [pathlib](https://docs.python.org/3/library/pathlib.html) more consistently (also enforced with Ruff's [PTH](https://docs.astral.sh/ruff/rules/#flake8-use-pathlib-pth) rule (except for modflow_devtools/zip.py)
- Refactor some aspects of `subprocess.run()` in `meson_build()` to not use `shell=True`. Also, run `meson compile ...` before `meson install ...`
- Apply some automated fixes from Ruff rules [C4](https://docs.astral.sh/ruff/rules/#flake8-comprehensions-c4), [RUF](https://docs.astral.sh/ruff/rules/#ruff-specific-rules-ruf) and [UP](https://docs.astral.sh/ruff/rules/#pyupgrade-up).
- Fix missing parameter in `test_fixtures.py::test_keep_function_scoped_tmpdir` (found via Ruff's …

refactor: use pathlib and subprocess; refactor other aspects

---

.github/workflows/ci.yml
.github/workflows/release.yml
.readthedocs.yml
DEVELOPER.md
README.md
autotest/test_misc.py
modflow_devtools/download.py
modflow_devtools/fixtures.py
modflow_devtools/latex.py
modflow_devtools/markers.py
modflow_devtools/misc.py
modflow_devtools/ostags.py
pyproject.toml
setup.py

This PR drops Python 3.8 support, and adds 3.13 to the test matrix. Other changes:
- Ruff's UP check automatically fixes some of the Python code for 3.9+
- Clean-up the `setup.py` wrapper file
- Some of the CI jobs have used `python-version: 3.x` to specify the latest stable version of Python
- Several steps of the CI workflow use conditionals `if: matrix.python != 3.8`, which are removed - is this the correct change?
- Upgrade ReadTheDocs configuration to use ubuntu-24.04 with python 3.13

chore: drop python 3.8, support 3.13

---

modflow_devtools/dfn.py

Only explicitly acknowledged variable attributes were parsed, we need them all

fix(dfn): include missing attributes

---

modflow_devtools/dfn.py

The `iper` variable was previously missed. It has `in_record true` but it's not in a record, as per mf6's definition, it's in the `period` block. I suppose `in_record` really means "is a child of a composite", which is in tension with the hard distinction mf6 makes between blocks and variables. In the TOML format we no longer need `in_record`.
IMO it's cleaner to just mark transient blocks as such instead of defining an extra `iper` index variable. This does mean that we will need to translate the transient flag back into "iper" terminology for the mf6io guide, e.g. for examples like
```
BEGIN PERIOD <iper>
[SAVE <rtype> <ocsetting>]
[PRINT <rtype> <ocsetting>]
END PERIOD
```

fix(dfn): mark transient blocks

---

modflow_devtools/dfn.py

Flopy expects this for `mfstructure.py` introspection. Keep it for now and drop it once flopy no longer needs it.

fix(dfn): keep block attribute for now

---

.github/workflows/ci.yml

@mwtoews any idea why `uvx pytest ...` might fail?

ci: update uv usage

---

autotest/test_models.py
modflow_devtools/models.py

expose the model mapping so consumers can ask which models are available without using `dir()`

feat: model mapping

---

autotest/test_models.py
modflow_devtools/make_registry.py
modflow_devtools/models.py
modflow_devtools/registry/examples.toml

Expose the grouping of example models into scenarios

feat(models): add example scenario mapping

---

modflow_devtools/models.py
pyproject.toml

https://github.com/fatiando/pooch/pull/415/files

fix: filelock when fetching zips

---

modflow_devtools/models.py

Network errors often crop up in CI. We want some resilience. Eventually it might be nice to make the retry count configurable somehow.

fix(models.py): add retries for transient network errors

---

docs/md/models.md
modflow_devtools/registry/examples.toml
modflow_devtools/registry/models.toml

Adopt a convention of prefixing model names with the model type (i.e. the program used to run it), e.g. "mf6/" or "mf2005/". Relative path parts below the initial prefix reflect the model's relative path within its repository.

refactor(registry): add mf6 prefix to mf6 model names

---

docs/md/models.md

docs(models): update models api docs

---

modflow_devtools/models.py

The LocalRegistry was described as lazy but it is eager.

docs(models): fix docstring

---

modflow_devtools/models.py

Allow providing more than one path to local registries. The registry becomes the union of models found in all the paths.

refactor(LocalRegistry): support multiple model directory paths

---

modflow_devtools/models.py

Sometimes you end up right where you started, a bit wiser for your travails

refactor(LocalRegistry): back to the old indexing pattern

---

modflow_devtools/misc.py
modflow_devtools/models.py

The parameter `prefix` is a string to prepend to model names. But the routine to search for model dirs also has a `prefix` param to filter the results. Switch the `prefix` parameter's semantics to match this, and pass it through, and add a new `model_name_prefix` parameter for model name modification.

refactor(LocalRegistry): rework index method prefix parameters

---

docs/md/models.md
modflow_devtools/make_registry.py
modflow_devtools/models.py
modflow_devtools/registry/examples.toml

Also make the model order in the examples mapping deterministic (and make sure gwf comes first)

refactor(make_registry.py): shortcut to create default registry

---

modflow_devtools/dfn.py

rename `Var` -> `Field` (and corresponding local variables) to standardize terminology. improve docstrings, miscellaneous tidying.

refactor(dfn): rename var -> field, misc cleanup

---

modflow_devtools/dfn.py
modflow_devtools/misc.py

In the new TOML definition file format, define period block variables (arrays) in terms of the grid and time discretization shape, rather than in the sparse/list-based input form with shape maxbound, the latter being an MF6 input file format detail. Towards structure-scoped TOML definition files i.e. connections/contents of simulation components, whereas normal DFN files are also about input formatting.
Sample of the old format as compared to the new for the GWF CHD period block:
```
block period
name iper
type integer
block_variable True
in_record true
tagged false
shape
valid
reader urword
optional false
longname stress period number
description REPLACE iper {}
block period
name stress_period_data
type recarray cellid head aux boundname
shape (maxbound)
reader urword
longname …
```

refactor(dfn): separate period block arrays in toml

---

modflow_devtools/dfn.py

`multi` attribute generalizes concept of multi-package to any component whose parent can have not just one but multiple

feat(dfn): mark models, exgs, slns multi-components in tomls
