modflow_devtools/download.py
modflow_devtools/test/test_download.py

- add method `download_artifact()`
- rename `get_artifacts()` to `list_artifacts()`
- refactor `download_and_unzip` auth mechanism
- add/update tests

refactor(misc)

---

modflow_devtools/download.py

Fixes an issue with the `download_and_unzip()` function causing downloaded files to be larger than they should be. Also restores retries for that fn (previously existed but lost in refactor from `requests` to `urllib`) and adds retries to `download_artifact()`.

fix(download): use 'wb' mode when writing downloads, add retries

---

modflow_devtools/executables.py
modflow_devtools/test/test_executables.py

- various refactoring/fixes to the executable targets container `Executables`
- simplify API and support dictionary-like as well as attribute-based access

refactor(executables): simplify exes container, allow dict access

---

.gitignore
.readthedocs.yml
README.md
docs/Makefile
docs/conf.py
docs/index.rst
docs/make.bat
docs/md/act.md
docs/md/cases.md
docs/md/doctoc.md
docs/md/download.md
docs/md/executables.md
docs/md/fixtures.md
docs/md/install.md
docs/md/markers.md
docs/md/zip.md
scripts/update_version.py
setup.cfg

Add ReadTheDocs configuration and move docs out of the README.

docs: set up ReadTheDocs

---

README.md
docs/md/zip.md

Add links to Python docs, relevant issue and PR.

docs: expand docs for MFZipFile

---

setup.cfg

The [PyPI description](https://pypi.org/project/modflow-devtools/) is currently the license &mdash; fix `setup.cfg` so it's the README instead. Also remove unused test files. There is one remaining empty, `test_zip.py`, but some tests for `MFZipFile` are incoming shortly.

chore: remove empty files, fix long description in setup.cfg

---

docs/md/fixtures.md
modflow_devtools/fixtures.py
modflow_devtools/test/test_misc.py

Discover external model repository folders with names ending in `.git`

feat(fixtures): discover external model repo dirs with .git suffix

---

docs/index.rst

docs: update index.rst

---

docs/index.rst
docs/md/timeit.md
modflow_devtools/misc.py
modflow_devtools/test/test_misc.py

- moved with slight modification from [modflow6-examples `common/config.py`](https://github.com/MODFLOW-USGS/modflow6-examples/blob/7219b2b3c40eb228a22c6f448080eb89cabd9d01/common/config.py#L41)
- add tests
- add docs

feat(timeit): add function timing decorator

---

pytest.ini

- c.f. https://github.com/modflowpy/flopy/pull/1967

ci: enable colorful pytest output

---

docs/md/download.md
docs/md/ostags.md

* fix `list_release_assets()` -> `get_release_assets()` in `download.md`
* fix `get_binary_suffixes()` example in `ostags.md`

docs: minor corrections

---

.github/workflows/ci.yml

see https://github.com/modflowpy/flopy/pull/1987

ci: remove branch filters from push trigger

---

modflow_devtools/executables.py

* don't break back-compatibility

refactor: re-export get_suffixes from executables module

---

.github/workflows/ci.yml
pyproject.toml

https://github.com/pytest-dev/pytest/releases/tag/8.1.0 broke some plugins and was yanked

chore(dependencies): restrict yanked pytest version 8.1.0

---

autotest/test_download.py
autotest/test_markers.py
autotest/test_misc.py
autotest/test_zip.py
modflow_devtools/download.py
modflow_devtools/fixtures.py
modflow_devtools/imports.py
modflow_devtools/misc.py
pyproject.toml
scripts/update_version.py

chore(format): add isort rule, enforce line length

---

autotest/test_fixtures.py
modflow_devtools/fixtures.py
modflow_devtools/misc.py

* multiple programs don't like this: gridgen, iris

fix(fixtures): don't use square brackets in tempdir paths

---

modflow_devtools/download.py

same fix as https://github.com/modflowpy/flopy/pull/2320

fix(download.py): accommodate missing gh api response item

---

docs/md/dfn.md
modflow_devtools/dfn.py
modflow_devtools/dfn2toml.py
modflow_devtools/misc.py

https://github.com/modflowpy/pyphoenix-project/discussions/47#discussioncomment-11856724

refactor(dfn): use explicit table names in toml format

---

autotest/test_dfn.py
modflow_devtools/dfn.py

- fix subpackage access
- blocks themselves at the top level, no top-level `blocks` section
- sort variable attributes
- drop some variable attributes I am pretty sure are unnecessary
- cleanup tests

refactor(dfn): minor toml format fixes/improvements

---

.github/workflows/ci.yml
README.md
modflow_devtools/dfn.py
modflow_devtools/dfn2toml.py
modflow_devtools/download.py
modflow_devtools/fixtures.py
modflow_devtools/imports.py
modflow_devtools/latex.py
modflow_devtools/make_registry.py
modflow_devtools/misc.py
modflow_devtools/models.py
modflow_devtools/snapshots.py
pyproject.toml

Add mypy to lint deps, fix some typing issues, type check in CI

chore: use mypy

---

README.md
pyproject.toml

And update features, remove commented line from pyproject.toml

docs(readme): fix table of contents

---

modflow_devtools/dfn.py

The foreign key system was to support flopy3's concept of "subpackage" but that should be a flopy concern rather than of the specification, though this leaves the `Ref` typed dict for now

refactor(dfn): drop fkeys from v2/toml

---

modflow_devtools/dfn.py

generalize the column separation in #229 from period block recarrays to all recarrays. deal only with arrays in the v2 schema.

feat(dfn): separate all recarray columns in tomls
